import{a as b,S as L,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const w="50307425-541b949c038afe75b2e77934f",v="https://pixabay.com/api/";async function S(o,r=1){const n={key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await b.get(v,{params:n})).data}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),q=new L(".gallery a",{captionsData:"alt"});function B(o){const r=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:t,views:i,comments:p,downloads:g})=>`
    <li class="gallery-item">
      <a href="${s}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${p}</p>
        <p><b>Downloads:</b> ${g}</p>
      </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",r),q.refresh()}function E(){u.innerHTML=""}function M(){f.classList.remove("is-hidden")}function P(){f.classList.add("is-hidden")}function $(){m.classList.remove("is-hidden")}function y(){m.classList.add("is-hidden")}const d=document.querySelector(".form"),O=document.querySelector(".load-more");let a=1,l="";d.addEventListener("submit",async o=>{o.preventDefault(),l=d.elements["search-text"].value.trim(),l&&(a=1,E(),y(),await h())});O.addEventListener("click",async()=>{a+=1,await h(!0)});async function h(o=!1){M();try{const{hits:r,totalHits:n}=await S(l,a);if(!r.length){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}B(r);const s=Math.ceil(n/15);if(a<s?$():(y(),c.info({message:"We're sorry, but you've reached the end of search results."})),o){const e=document.querySelector(".gallery").firstElementChild,{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}catch{c.error({title:"Error",message:"Something went wrong!"})}finally{P()}}
//# sourceMappingURL=index.js.map
